# Generated by Django 2.2 on 2019-05-01 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood_test_data',
            old_name='Treg1',
            new_name='Treg0',
        ),
    ]
