# Generated by Django 2.2 on 2019-05-01 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20190501_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood_test_data',
            old_name='Treg0',
            new_name='Treg1',
        ),
    ]
